# Generated by Django 2.1.1 on 2020-12-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergencyContactId', models.IntegerField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('sendDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('mailaddress', models.EmailField(max_length=254)),
                ('subMailaddress', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafetyConf.Group'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='destinationGroupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafetyConf.Group'),
        ),
        migrations.AddField(
            model_name='answer',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SafetyConf.Employee'),
        ),
    ]
